name: Dropinfo
version: 1.0.1
main: vip.lanxing.mingxuan.dropinfo.Dropinfo
api-version: 1.21
folia-supported: true
description: Display item names for dropped entities with Folia support
authors:
  - Lanxing
commands:
  dropinfo:
    description: Reload plugin configuration
    aliases: [di]
permissions:
  dropinfo.reload:
    description: Allows reloading the plugin
    default: op